name: WinDesign
version: '${project.version}'
main: im.paul.windesign.WinDesign
api-version: '1.16'
depend:
  - LuckPerms
  - PlayerPoints
softdepend:
  - TAB
commands:
  windesign:
  brackets:
  prefix:
  tag:
  namecolor:

permissions:
  windesign.admin:
    default: op
  windesign.admin.clear:
    default: op

